"""empty message

Revision ID: 99f2f6606b4f
Revises: 3ffe90590d36
Create Date: 2024-10-12 15:56:32.799390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99f2f6606b4f'
down_revision = '3ffe90590d36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_class_metrics', schema=None) as batch_op:
        batch_op.drop_constraint('job_class_metrics_metric_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('job_class_metrics_job_class_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'metrics', ['metric_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'job_classes', ['job_class_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_class_metrics', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('job_class_metrics_job_class_id_fkey', 'job_classes', ['job_class_id'], ['id'])
        batch_op.create_foreign_key('job_class_metrics_metric_id_fkey', 'metrics', ['metric_id'], ['id'])

    # ### end Alembic commands ###
